server:
  port: 5001  # 端口号

spring:
  application:
    name: alibaba-service-consumer   # 服务名
  cloud:
    nacos:
      discovery:
       server-adder: 127.0.0.1:8848  # Nacos server 的地址

service:
  url: http://alibaba-service-provider    # 服务提供者的服务名