server:
    port: 7001 # 端口
spring:
    application:
      name: service-sentinel # 服务名
    cloud:
      nacos:
        discovery:
          # Nacos 服务注册中心(集群)地址
          server-addr: 127.0.0.1:8848
      sentinel:
        transport:
          # 配置 Sentinel dashboard 地址
          dashboard: 127.0.0.1:8080
          # 默认 8719 端口，假如被占用会自动从 8719 开始依次+1扫描, 直至找到未被占用的端口
          port: 8719
management:
    endpoints:
      web:
        exposure:
          include: '*'